2025-05-18 20:02:06,837 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-18 20:02:06,838 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando unna nueva mascota o dueño: 'str' object has no attribute 'str'
2025-05-18 20:06:42,718 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-18 20:06:42,720 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: 'bool' object has no attribute 'isdigit'
2025-05-18 20:08:46,343 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueño: Número de teléfono inválido
2025-05-18 20:08:46,345 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-18 20:09:24,321 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-18 20:09:24,321 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: 'bool' object has no attribute 'isdigit'
2025-05-18 20:11:30,546 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-18 20:14:09,668 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-18 20:14:09,669 - INFO - clinica_veterinaria - La mascota {self.nombre} se ha creado exitosamente.
2025-05-18 20:15:21,921 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueño: Número de teléfono inválido
2025-05-18 20:15:21,922 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-18 20:18:23,424 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueno: Numero de telefono invalido
2025-05-18 20:18:23,427 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Numero de telefono invalido
2025-05-18 20:22:29,137 - ERROR - clinica_veterinaria - Ha ocurrido un error en el menú, vuelva a intentar.
2025-05-18 20:26:02,844 - ERROR - clinica_veterinaria - Ha ocurrido un error en el menu, vuelva a intentar.
2025-05-18 20:26:02,845 - INFO - clinica_veterinaria - Se vuelve a iniciar el menu.
2025-05-18 20:28:45,176 - CRITICAL - clinica_veterinaria - Ha ocurrido un error en el menu, vuelva a intentar.
2025-05-18 20:29:21,298 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueno: El argumento no puede estar vacio.
2025-05-18 20:29:21,298 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: El argumento no puede estar vacio.
2025-05-18 20:30:36,654 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño A
2025-05-18 20:30:36,655 - ERROR - clinica_veterinaria - Ha ocurrido un error creaando la mascota: El argumento no puede estar vacio.
2025-05-18 20:30:36,655 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: El argumento no puede estar vacio.
2025-05-18 20:33:23,663 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-18 20:36:21,921 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-18 20:37:01,325 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-18 20:37:01,325 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-18 20:37:09,609 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 20:37:43,267 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota parcerito sin nombre registrado
2025-05-18 20:38:40,385 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-18 20:39:22,157 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-18 20:39:22,157 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-18 20:39:49,038 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-18 20:40:31,899 - ERROR - clinica_veterinaria - Fecha invalida ingresada: '12' -> time data '12' does not match format '%d/%m/%Y'
2025-05-18 20:40:31,899 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacio.
2025-05-18 20:42:27,820 - WARNING - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-18 20:45:40,344 - WARNING - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-18 20:47:03,020 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-18 20:47:03,022 - INFO - clinica_veterinaria - La mascota A se ha creado exitosamente.
2025-05-18 20:47:08,932 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota A sin nombre registrado
2025-05-18 20:47:42,326 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 20:47:57,716 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota A sin nombre registrado
2025-05-18 20:48:45,907 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 20:50:39,705 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-18 20:50:39,705 - INFO - clinica_veterinaria - La mascota A se ha creado exitosamente.
2025-05-18 20:50:42,450 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 20:51:07,314 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-18 20:51:15,971 - WARNING - clinica_veterinaria - Mascota a sin historial registrado
2025-05-18 21:02:29,017 - INFO - clinica_veterinaria - La mascota Parcerito fue asignada a un dueño ya existente (B).
2025-05-18 21:02:29,018 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-18 21:02:57,065 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-18 21:03:16,137 - WARNING - clinica_veterinaria - Mascota a sin historial registrado
2025-05-18 21:03:21,355 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 21:03:23,082 - INFO - clinica_veterinaria - Mascotas listadas con exito.
2025-05-18 21:04:15,206 - ERROR - clinica_veterinaria - Fecha invalida ingresada: '' -> time data '' does not match format '%d/%m/%Y'
2025-05-18 21:04:15,206 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacio.
2025-05-18 21:04:21,447 - ERROR - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-19 14:49:35,208 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-19 14:49:35,212 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 14:50:25,697 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-19 14:51:11,560 - ERROR - clinica_veterinaria - Fecha inválida ingresada: '' -> time data '' does not match format '%d/%m/%Y'
2025-05-19 14:51:11,561 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacío.
2025-05-19 14:51:25,713 - ERROR - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-19 14:53:08,307 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-19 14:54:35,244 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueno: El argumento no puede estar vacío.
2025-05-19 14:54:35,244 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: El argumento no puede estar vacío.
2025-05-19 14:55:39,231 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-19 14:55:39,232 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 14:56:09,257 - ERROR - clinica_veterinaria - Fecha inválida ingresada: '01/187/1' -> time data '01/187/1' does not match format '%d/%m/%Y'
2025-05-19 14:56:09,257 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-19 14:57:08,028 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-19 14:57:46,513 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-19 14:57:46,514 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 14:57:57,305 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Parcerit sin nombre registrado.
2025-05-19 14:58:14,555 - ERROR - clinica_veterinaria - Fecha inválida ingresada: '01/187/1' -> time data '01/187/1' does not match format '%d/%m/%Y'
2025-05-19 14:58:14,555 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-19 14:59:53,079 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-19 15:02:01,457 - ERROR - clinica_veterinaria - Fecha inválida ingresada: '' -> time data '' does not match format '%d/%m/%Y'
2025-05-19 15:02:01,457 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacío.
2025-05-19 15:02:37,041 - ERROR - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-19 15:04:11,148 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-19 15:04:11,148 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 15:04:29,573 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacío.
2025-05-19 15:04:39,893 - ERROR - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-19 15:05:23,000 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-19 15:05:23,000 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 15:05:43,122 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: El argumento no puede estar vacío.
2025-05-19 15:05:49,639 - ERROR - clinica_veterinaria - Error al mostrar historial: 'Consulta' object has no attribute 'mascota'
2025-05-19 15:31:10,389 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-19 15:31:10,389 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-19 15:31:24,196 - ERROR - clinica_veterinaria - Fecha inválida ingresada: '' -> time data '' does not match format '%d/%m/%Y'
2025-05-19 15:31:24,196 - ERROR - clinica_veterinaria - Ha ocurrido un error al registrar la consulta: Formato de fecha inválido. Use dd/mm/aaaa.
2025-05-19 15:31:24,196 - ERROR - clinica_veterinaria - Error al registrar consulta: Formato de fecha inválido. Use dd/mm/aaaa.
2025-05-19 15:31:48,208 - WARNING - clinica_veterinaria - Mascota Parcerito sin historial registrado.
2025-05-22 21:16:59,937 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 21:19:50,651 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Jorim
2025-05-22 21:19:50,652 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 21:20:04,858 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Pepito sin nombre registrado.
2025-05-22 21:21:30,849 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Jerom
2025-05-22 21:21:30,850 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 21:21:38,075 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Pepito sin nombre registrado.
2025-05-22 21:21:53,130 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Pepito sin nombre registrado.
2025-05-22 21:22:08,755 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-22 21:27:26,302 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 21:28:01,072 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 21:28:45,090 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Jerome
2025-05-22 21:28:45,091 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 21:28:52,786 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Pepito sin nombre registrado.
2025-05-22 21:33:04,990 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 21:33:27,177 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 21:33:52,885 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Erom
2025-05-22 21:33:52,885 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 21:33:59,766 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota Pepito sin nombre registrado.
2025-05-22 21:34:33,209 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 21:35:28,828 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 21:36:00,898 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Eronm
2025-05-22 21:36:00,899 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 21:36:32,162 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 21:37:47,306 - WARNING - clinica_veterinaria - Cuidado, nombre de mascota no encontrado.
2025-05-22 21:43:02,591 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 22:02:46,249 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueno: El argumento no puede estar vacío.
2025-05-22 22:04:21,076 - ERROR - clinica_veterinaria - Ha ocurrido el siguiente error al registrar el dueno: Número de teléfono inválido
2025-05-22 22:09:28,506 - INFO - clinica_veterinaria - La mascota Erom se ha creado exitosamente.
2025-05-22 22:09:28,536 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 22:10:49,289 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Jerom
2025-05-22 22:10:49,289 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-22 22:36:21,654 - CRITICAL - clinica_veterinaria - Ha ocurrido un error fatal en el menu.
2025-05-22 22:37:50,783 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-22 22:38:20,304 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Jero
2025-05-22 22:38:20,304 - INFO - clinica_veterinaria - La mascota Pepito se ha creado exitosamente.
2025-05-23 20:04:14,171 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-23 20:05:06,710 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcerote
2025-05-23 20:05:06,711 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-23 20:05:06,712 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: [Errno 2] No such file or directory: 'data/Mascota.csv'
2025-05-23 20:06:16,793 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-23 20:07:03,396 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-23 20:07:03,396 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-23 20:07:03,397 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: [Errno 2] No such file or directory: '../data/Mascota.csv'
2025-05-23 20:10:20,517 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-23 20:10:44,268 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-23 20:11:19,191 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-23 20:11:19,192 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-23 20:18:27,733 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-23 20:19:07,639 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-23 21:51:38,360 - INFO - clinica_veterinaria - Mascotas listadas desde CSV con éxito.
2025-05-23 21:51:55,586 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-23 21:52:39,122 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 40, in main
    accion = int(input("Porfavor ingrese una opción (1-5): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-05-23 21:52:49,081 - INFO - clinica_veterinaria - Mascotas listadas desde CSV con éxito.
2025-05-23 21:54:53,356 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-23 21:56:53,433 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Dueñoso
2025-05-23 21:56:53,433 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: El argumento nombre no puede estar vacío.
2025-05-23 21:58:11,118 - INFO - clinica_veterinaria - La mascota Danny fue asignada a un dueño ya existente (Dueñoso).
2025-05-23 21:58:11,118 - INFO - clinica_veterinaria - La mascota Danny se ha creado exitosamente.
2025-05-23 21:58:53,182 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-23 22:07:35,174 - ERROR - clinica_veterinaria - Error al mostrar mascotas desde CSV: 'dueno_documento'
2025-05-23 22:07:40,384 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-25 20:40:52,130 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-25 20:40:52,131 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-25 20:41:15,029 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-25 20:41:15,030 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-25 20:41:33,762 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-25 21:11:56,824 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-25 21:11:56,824 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-25 21:12:11,521 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-29 19:09:46,072 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-29 19:09:46,072 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-29 19:09:46,072 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 19:09:46,072 - ERROR - clinica_veterinaria - El archivo consultas.json no existe. Imposible cargar la información.
2025-05-29 19:11:16,059 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-29 19:11:16,059 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-29 19:11:16,059 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 19:11:16,060 - ERROR - clinica_veterinaria - El archivo consultas.json no existe. Imposible cargar la información.
2025-05-29 19:11:41,644 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-29 19:12:19,837 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:12:19,838 - INFO - clinica_veterinaria - Se han guardado las consultas correctamente.
2025-05-29 19:13:22,168 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota  sin nombre registrado.
2025-05-29 19:13:22,169 - INFO - clinica_veterinaria - Se han guardado las consultas correctamente.
2025-05-29 19:13:49,982 - INFO - clinica_veterinaria - La mascota Parcerito fue asignada a un dueño ya existente (Max).
2025-05-29 19:13:49,983 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-29 19:14:40,586 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:14:40,587 - INFO - clinica_veterinaria - Se han guardado las consultas correctamente.
2025-05-29 19:15:12,484 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-29 19:15:12,485 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-29 19:15:12,485 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-29 19:15:12,485 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 19:15:12,488 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:15:12,488 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:15:12,488 - INFO - clinica_veterinaria - Información de consultas cargada satisfactoriamente.
2025-05-29 19:15:59,271 - WARNING - clinica_veterinaria - Mascota Parcerito sin historial registrado.
2025-05-29 19:18:36,261 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Max
2025-05-29 19:18:36,261 - INFO - clinica_veterinaria - La mascota Homero se ha creado exitosamente.
2025-05-29 19:18:36,261 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-29 19:18:36,261 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 19:18:36,265 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:18:36,265 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-29 19:18:36,265 - INFO - clinica_veterinaria - Información de consultas cargada satisfactoriamente.
2025-05-29 19:20:15,481 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 19:20:15,482 - WARNING - clinica_veterinaria - Se han borrado las consultas.
2025-05-29 19:20:23,747 - WARNING - clinica_veterinaria - No hay mascota registrada.
2025-05-29 19:20:28,277 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 19:20:34,813 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 19:20:34,814 - INFO - clinica_veterinaria - Información de consultas cargada satisfactoriamente.
2025-05-29 19:20:42,470 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:04:16,266 - INFO - clinica_veterinaria - Se cargo la información orrectamente
2025-05-29 20:04:16,267 - INFO - clinica_veterinaria - Información de consultas cargada satisfactoriamente.
2025-05-29 20:04:21,748 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:04:21,750 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:04:21,750 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:06:31,432 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-29 20:06:31,434 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:06:31,436 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:06:31,437 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:07:06,824 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-29 20:07:06,826 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:07:06,828 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:07:06,828 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:12:22,369 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-29 20:12:22,371 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:12:22,372 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:12:22,373 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:12:44,431 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-29 20:12:44,433 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:12:44,435 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:12:44,435 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-29 20:13:26,997 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-29 20:13:26,999 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-29 20:13:27,001 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-29 20:13:27,001 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:21:46,355 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:21:46,357 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:21:46,358 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:21:46,359 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:25:12,012 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:25:12,014 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:25:12,016 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:25:12,017 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:34:27,164 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:34:27,167 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:34:27,168 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:34:27,171 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:44:29,601 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:44:29,603 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:44:29,604 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:44:29,614 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:44:29,616 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:44:47,212 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:44:47,215 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:44:47,217 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:44:47,221 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-30 18:44:47,223 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:46:54,218 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:46:54,221 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:46:54,222 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:46:54,222 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:46:54,223 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:48:36,987 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:48:36,991 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:48:36,992 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:48:36,992 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:48:36,993 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:49:02,588 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:49:02,590 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:49:02,592 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:49:02,592 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:49:02,593 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:52:07,742 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:07,744 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:52:07,746 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:07,746 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:52:07,747 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:52:49,648 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:49,650 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:52:49,652 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:49,652 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:52:49,653 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:52:49,653 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:49,653 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:52:49,654 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:49,654 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:52:49,654 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:52:49,654 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:52:49,654 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:15,265 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:15,267 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:53:15,268 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:15,268 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:15,269 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:24,789 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:24,792 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:53:24,794 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:24,794 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:24,795 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:53:24,795 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:24,795 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:24,795 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:24,796 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:53:24,796 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:53:24,796 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:53:24,796 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,279 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,281 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:55:36,283 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,283 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,284 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,286 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,286 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,288 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,288 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,290 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,290 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,291 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,291 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,291 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,291 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:55:36,293 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:55:36,293 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,806 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,809 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:56:37,810 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,810 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,811 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,812 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,812 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,813 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,813 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,814 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,814 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,814 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,814 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,814 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,815 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,815 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:37,815 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:37,815 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,482 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,485 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 18:56:53,486 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,487 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,487 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,488 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,489 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,489 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,490 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,491 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,491 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,491 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,492 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,492 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,492 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,492 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,493 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 18:56:53,493 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 18:56:53,493 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,545 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:03:47,546 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:03:47,546 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,548 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:03:47,550 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,550 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,551 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:03:47,551 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,551 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,551 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,552 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,552 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:03:47,552 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,552 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,552 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,553 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,553 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,555 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,555 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,555 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,555 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,556 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,556 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,556 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,556 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,557 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:03:47,557 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:03:47,557 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,381 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:04:56,382 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:04:56,382 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,384 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:04:56,386 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,386 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,387 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:04:56,388 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,943 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,945 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:08:23,947 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,947 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,948 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,949 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,949 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,950 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,951 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,951 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,951 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:08:23,951 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:08:23,951 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,564 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,566 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:09:33,568 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,568 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,569 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,570 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,571 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,572 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:09:33,572 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:09:33,572 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,909 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:15:31,909 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,912 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:15:31,912 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:15:31,913 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,913 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:15:31,913 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,916 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:15:31,918 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,918 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,919 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:15:31,920 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,920 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,920 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,920 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:15:31,921 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,738 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:16:52,738 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,741 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:16:52,741 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:16:52,741 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,742 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:16:52,742 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,744 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:16:52,745 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,745 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,746 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:16:52,747 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,747 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,747 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,747 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,747 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:16:52,748 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,068 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:17:53,068 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,072 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:17:53,072 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:17:53,072 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,073 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:17:53,073 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,075 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:17:53,076 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,076 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,076 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,077 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:17:53,078 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,924 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:18:04,924 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,927 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:18:04,928 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:18:04,928 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,928 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:18:04,929 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,930 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:18:04,932 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,932 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,933 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,934 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:18:04,935 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,157 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:17,157 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,160 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:17,161 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:17,161 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,162 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:17,162 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,164 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:17,165 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,165 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,166 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:17,166 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,166 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,166 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:17,167 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,073 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:30,073 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,076 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:30,076 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:30,076 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,077 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:30,077 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,079 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:30,080 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,081 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,081 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:30,082 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,946 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:31,946 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,949 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:31,950 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:31,950 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,951 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:31,951 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,953 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:31,954 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,954 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,955 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:31,955 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,955 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,956 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,957 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,958 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,958 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,958 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:31,958 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:31,958 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,216 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:33,216 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,219 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:33,220 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:33,220 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,220 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:33,221 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,223 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:33,224 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,224 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,225 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,226 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,227 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,228 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:33,228 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:33,228 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,409 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:34,410 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,413 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:34,414 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:34,414 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,414 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:34,415 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,416 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:34,418 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,418 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:34,419 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,420 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:34,421 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,489 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:35,489 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,492 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:35,493 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:35,493 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,494 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:35,494 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,495 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:35,496 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,496 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,497 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:35,497 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,497 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,497 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:35,498 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,521 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:36,521 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,524 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-30 19:25:36,525 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-05-30 19:25:36,525 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,525 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota NoExiste sin nombre registrado.
2025-05-30 19:25:36,525 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,527 - INFO - clinica_veterinaria - Se borro la información correctamente
2025-05-30 19:25:36,528 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,528 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Intento de listar mascotas sin haber registrado ninguna.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,529 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-30 19:25:36,530 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-05-31 19:41:14,026 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 19:41:14,029 - CRITICAL - clinica_veterinaria - Error inesperado en main: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 516, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\_collections.py", line 345, in __missing__
    self[key] = val = self.creator(key)
                      ~~~~~~~~~~~~^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 484, in _access_cls
    return self.fallback[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'Dueno'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 59, in crear_mascota
    nueva_mascota = Mascota(nombre_mascota, especie_mascota, raza_mascota, edad_mascota, dueno)
  File "<string>", line 4, in __init__
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
    ~~^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4406, in _event_on_init
    instrumenting_mapper._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1656, in do_init
    self._setup_entity()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1866, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 520, in _resolve_name
    self._raise_for_name(name, err)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 501, in _raise_for_name
    raise exc.InvalidRequestError(
    ...<5 lines>...
    ) from err
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
2025-05-31 19:47:42,364 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 19:47:42,365 - CRITICAL - clinica_veterinaria - Error inesperado en main: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 516, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\_collections.py", line 345, in __missing__
    self[key] = val = self.creator(key)
                      ~~~~~~~~~~~~^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 484, in _access_cls
    return self.fallback[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'Dueno'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 59, in crear_mascota
    nueva_mascota = Mascota(nombre_mascota, especie_mascota, raza_mascota, edad_mascota, dueno)
  File "<string>", line 4, in __init__
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
    ~~^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4406, in _event_on_init
    instrumenting_mapper._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1656, in do_init
    self._setup_entity()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1866, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 520, in _resolve_name
    self._raise_for_name(name, err)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 501, in _raise_for_name
    raise exc.InvalidRequestError(
    ...<5 lines>...
    ) from err
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
2025-05-31 19:56:53,213 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 35, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-05-31 19:57:27,015 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: Número de teléfono inválido
2025-05-31 19:57:46,158 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-31 19:57:46,159 - CRITICAL - clinica_veterinaria - Error inesperado en main: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 516, in _resolve_name
    rval = d[token]
           ~^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\_collections.py", line 345, in __missing__
    self[key] = val = self.creator(key)
                      ~~~~~~~~~~~~^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 484, in _access_cls
    return self.fallback[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: 'Dueno'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 59, in crear_mascota
    nueva_mascota = Mascota(nombre_mascota, especie_mascota, raza_mascota, edad_mascota, dueno)
  File "<string>", line 4, in __init__
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
    ~~^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4406, in _event_on_init
    instrumenting_mapper._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1656, in do_init
    self._setup_entity()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1866, in _setup_entity
    self._clsregistry_resolve_name(argument)(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 520, in _resolve_name
    self._raise_for_name(name, err)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\clsregistry.py", line 501, in _raise_for_name
    raise exc.InvalidRequestError(
    ...<5 lines>...
    ) from err
sqlalchemy.exc.InvalidRequestError: When initializing mapper Mapper[Mascota(mascotas)], expression 'Dueno' failed to locate a name ('Dueno'). If this is a class name, consider adding this relationship() to the <class 'models.mascota.Mascota'> class after both dependent classes have been defined.
2025-05-31 20:03:04,289 - CRITICAL - clinica_veterinaria - Error inesperado en main: Mapper 'Mapper[Mascota(mascotas)]' has no property 'consultas'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2522, in get_property
    return self._props[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'consultas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 56, in crear_mascota
    dueno = Dueno(nombre_dueno, telefono_dueno, direccion_dueno, documento_dueno)
  File "<string>", line 4, in __init__
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    manager.dispatch.init(self, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
    ~~^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4406, in _event_on_init
    instrumenting_mapper._check_configure()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2401, in _check_configure
    _configure_registries({self.registry}, cascade=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4214, in _configure_registries
    _do_configure_registries(registries, cascade)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 4255, in _do_configure_registries
    mapper._post_configure_properties()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2418, in _post_configure_properties
    prop.init()
    ~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\interfaces.py", line 589, in init
    self.do_init()
    ~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1661, in do_init
    self._generate_backref()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 2145, in _generate_backref
    self._add_reverse_property(self.back_populates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\relationships.py", line 1592, in _add_reverse_property
    other = self.mapper.get_property(key, _configure_mappers=False)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\mapper.py", line 2524, in get_property
    raise sa_exc.InvalidRequestError(
    ...<3 lines>...
    ) from err
sqlalchemy.exc.InvalidRequestError: Mapper 'Mapper[Mascota(mascotas)]' has no property 'consultas'.  If this property was indicated from other mappers or configure events, ensure registry.configure() has been called.
2025-05-31 20:09:13,421 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 20:09:13,421 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-31 20:09:13,427 - CRITICAL - clinica_veterinaria - Error inesperado en main: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 64, in crear_mascota
    session.commit()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 68, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 223, in _organize_states_for_save
    for state, dict_, mapper, connection in _connections_for_states(
                                            ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper, uowtransaction, states
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1753, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "<string>", line 2, in connection
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1039, in connection
    return self._connection_for_bind(bind, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1175, in _connection_for_bind
    conn = self._parent._connection_for_bind(
        bind, execution_options
    )
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        err, dialect, engine
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2436, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 625, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-31 20:21:24,757 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 20:21:24,757 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-31 20:21:24,771 - CRITICAL - clinica_veterinaria - Error inesperado en main: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('123456789', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: duenos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 64, in crear_mascota
    session.commit()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('123456789', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-31 20:31:19,817 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 20:31:19,817 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-31 20:31:19,821 - CRITICAL - clinica_veterinaria - Error inesperado en main: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('123456789', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: duenos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 64, in crear_mascota
    session.commit()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('123456789', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-31 20:33:52,526 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 20:33:52,527 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-31 20:33:52,530 - CRITICAL - clinica_veterinaria - Error inesperado en main: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('1234567890', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: duenos

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 39, in main
    crear_mascota(mascotas, duenos)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\services\gestion.py", line 64, in crear_mascota
    session.commit()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
        statement, multiparams, execution_options=execution_options
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python313\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: duenos
[SQL: INSERT INTO duenos (documento, nombre, telefono, direccion) VALUES (?, ?, ?, ?)]
[parameters: ('1234567890', 'Parcero', '1234567890', 'Calle 1')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-31 20:37:58,957 - INFO - clinica_veterinaria - Iniciando creación de base de datos...
2025-05-31 20:37:58,958 - INFO - clinica_veterinaria - Tabla encontrada: duenos
2025-05-31 20:37:58,958 - INFO - clinica_veterinaria - Tabla encontrada: mascotas
2025-05-31 20:37:58,958 - INFO - clinica_veterinaria - Tabla encontrada: consultas
2025-05-31 20:37:59,000 - INFO - clinica_veterinaria - Tablas creadas: ['consultas', 'duenos', 'mascotas']
2025-05-31 20:37:59,000 - INFO - clinica_veterinaria - Tablas creadas correctamente.
2025-05-31 20:47:53,819 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño B
2025-05-31 20:47:53,820 - INFO - clinica_veterinaria - La mascota A se ha creado exitosamente.
2025-05-31 20:49:25,958 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 35, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-05-31 20:49:54,130 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 20:54:49,353 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 35, in main
    listar_mascotas()
     ~~~~~~~~~~~~~~^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-05-31 20:55:16,067 - ERROR - clinica_veterinaria - Ha ocurrido un error registrando una nueva mascota o dueño: El argumento nombre no puede estar vacío.
2025-05-31 20:55:45,065 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 20:56:14,247 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-05-31 20:58:57,960 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 27, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-05-31 20:59:03,940 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 21:00:19,215 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 21:59:51,516 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Kim nam joon
2025-05-31 21:59:51,517 - INFO - clinica_veterinaria - La mascota Caramelo waou de la triñinidad tercero se ha creado exitosamente.
2025-05-31 22:00:27,238 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 22:02:18,280 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 22:03:27,489 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Parcero
2025-05-31 22:03:27,490 - INFO - clinica_veterinaria - La mascota Parcerito se ha creado exitosamente.
2025-05-31 22:03:30,249 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 22:05:31,988 - WARNING - clinica_veterinaria - Mascota Parcerito sin historial registrado.
2025-05-31 22:09:16,271 - WARNING - clinica_veterinaria - Cuidado, intento de buscar mascota  sin nombre registrado.
2025-05-31 22:09:23,357 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-05-31 22:11:18,813 - ERROR - clinica_veterinaria - Error al registrar consulta: Formato de fecha inválido. Use dd/mm/aaaa.
2025-05-31 22:12:17,167 - INFO - clinica_veterinaria - La consulta se ha registrado correctamente.
2025-06-01 18:06:18,115 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-06-01 18:06:18,116 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,118 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Juan pérez
2025-06-01 18:06:18,118 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,119 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - La mascota Max se ha creado exitosamente.
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,122 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - Se ha registrado exitosamente el dueño Carlos
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-01 18:06:18,123 - INFO - clinica_veterinaria - La mascota Firulais se ha creado exitosamente.
2025-06-05 21:19:03,802 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 21:21:37,937 - INFO - clinica_veterinaria - Mascota A actualizada.
2025-06-05 21:21:47,500 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 21:35:29,910 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-05 21:37:27,172 - INFO - clinica_veterinaria - Dueño 123456789 actualizado.
2025-06-05 21:38:34,963 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 21:39:06,160 - INFO - clinica_veterinaria - Consulta actualizada para la mascota Betún.
2025-06-05 21:50:01,884 - INFO - clinica_veterinaria - Mascota Parcerito actualizada.
2025-06-05 21:50:06,702 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 22:26:38,481 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 31, in main
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-05 22:27:29,202 - INFO - clinica_veterinaria - Mascota Parcerito eliminada exitosamente junto con 0 consultas.
2025-06-05 22:27:34,737 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 22:28:13,573 - INFO - clinica_veterinaria -  Dueños listados con éxito.
2025-06-05 22:30:13,551 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-05 22:31:41,860 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-05 22:31:59,541 - ERROR - clinica_veterinaria - Error inesperado al eliminar dueno: type object 'Mascota' has no attribute 'dueno_id'
2025-06-13 15:20:42,867 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-13 15:21:18,146 - ERROR - clinica_veterinaria - Error inesperado al eliminar dueno: type object 'Mascota' has no attribute 'dueno_id'
2025-06-13 15:21:44,472 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 15:28:45,449 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 15:29:08,056 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 15:29:25,450 - WARNING - clinica_veterinaria - Intento de eliminar dueño Parcero con 2 mascotas asociadas.
2025-06-13 15:29:49,683 - WARNING - clinica_veterinaria - Intento de eliminar dueño Miguel Arroz con 2 mascotas asociadas.
2025-06-13 15:31:30,628 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 15:31:46,903 - ERROR - clinica_veterinaria - Error inesperado al eliminar dueno: SQL expression element or literal value expected, got <models.dueno.Dueno object at 0x000001DC87A80830>.
2025-06-13 15:32:55,893 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 15:34:27,745 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 15:34:49,879 - INFO - clinica_veterinaria - Dueño Parcero (documento: 1033260414) eliminado exitosamente.
2025-06-13 15:34:55,274 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 15:36:36,137 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: 'clear'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'clear'
2025-06-13 15:37:44,940 - INFO - clinica_veterinaria - Dueño 123456789 actualizado.
2025-06-13 15:40:57,556 - INFO - clinica_veterinaria - Dueño 123456789 actualizado.
2025-06-13 15:43:17,243 - INFO - clinica_veterinaria - Dueño 123456789 actualizado.
2025-06-13 16:01:07,481 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 16:01:17,000 - ERROR - clinica_veterinaria - Error al listar dueno: 'Dueno' object has no attribute 'especie'
2025-06-13 16:09:52,080 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 16:10:45,574 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 16:10:56,048 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 16:12:21,165 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 16:12:40,272 - INFO - clinica_veterinaria - Mascotas listadas con éxito.
2025-06-13 16:13:51,951 - CRITICAL - clinica_veterinaria - Error inesperado en main: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
Traceback (most recent call last):
  File "c:\Users\Usuario\Intento de estudiar\Python-Talleres-Fundamentos\gestion_clinica_veterinaria\main.py", line 30, in main
    accion = int(input("Por favor ingrese una opción (1-6): "))
             ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '& C:/Users/Usuario/AppData/Local/Programs/Python/Python313/python.exe "c:/Users/Usuario/Intento de estudiar/Python-Talleres-Fundamentos/gestion_clinica_veterinaria/main.py"'
2025-06-13 16:13:56,751 - INFO - clinica_veterinaria - Dueños listados con éxito.
2025-06-13 16:14:15,283 - INFO - clinica_veterinaria - Eliminación masiva completada: 2 consultas, 2 mascotas, 2 dueños.
